name: my_job
description: We are going to use this to try a build
phases:
  fetch_source:
    main:
      type: git
      config:
        executable: /usr/local/bin/git
        repository: https://github.com/marcelog/erlci
  fetch_dependencies:
    main:
      type: rebar
      config:
        source_directory: erlci
        executable: /usr/local/bin/rebar3
  static_analysis:
    dialyzer:
      type: rebar
      config:
        task: dialyzer
        source_directory: erlci
        executable: /usr/local/bin/rebar3
    xref:
      type: rebar
      config:
        task: xref
        source_directory: erlci
        executable: /usr/local/bin/rebar3
  generate_doc:
    main:
      type: rebar
      config:
        source_directory: erlci
        executable: /usr/local/bin/rebar3
  create_artifacts:
    main:
      type: cmd
      config:
        shell: /bin/bash
        executable: /usr/bin/tar
        args:
          - zcf
          - erlci.tar.bz2
          - "*"