name: my_job
description: We are going to use this to try a build
variables:
  repo: https://github.com/marcelog/erlci
  src_dir: erlci
triggers:
  git_poll:
    expression: "*/1 * * * *"
    executable: {{git_location}}
    repository: {{repo}}
  cron:
    expression: "*/1 * * * *"
phases:
  fetch_source:
    main:
      type: git
      config:
        executable: {{git_location}}
        repository: {{repo}}
  fetch_dependencies:
    main:
      type: rebar
      config:
        source_directory: {{src_dir}}
        executable: {{rebar_location}}
  static_analysis:
    dialyzer:
      type: rebar
      config:
        task: dialyzer
        source_directory: {{src_dir}}
        executable: {{rebar_location}}
    xref:
      type: rebar
      config:
        task: xref
        source_directory: {{src_dir}}
        executable: {{rebar_location}}
  generate_doc:
    main:
      type: rebar
      config:
        source_directory: {{src_dir}}
        executable: {{rebar_location}}
  create_artifacts:
    main:
      type: cmd
      config:
        shell: {{bash}}
        executable: /usr/bin/tar
        args:
          - zcf
          - erlci.tar.bz2
          - "*"